### ISSUE TITLE
再生終了後も戻るボタンと進むボタンが消えない

### ISSUE THREAD

**Issue by fnmgithub** [sakkuntyo/discord-sktrythmjs2#7]

**Comment by sakkuntyo** [comment]
https://github.com/sakkuntyo/discord-sktrythmjs2/commit/8b934a4a89e6dfce652ba539aeb661ccd689cb98

**Comment by sakkuntyo** [comment]
なぜかエラーが出る
https://github.com/sakkuntyo/discord-sktrythmjs2/blob/f03a4efe4fcb071d36b11aead0a731490789eef6/src/main.ts#L177

![image](https://user-images.githubusercontent.com/20591351/233832545-2b165359-a811-42ae-8417-e2304bb13d8e.png)

2267 DiscordAPIError[10008]: Unknown Message$
2268     at handleErrors (/root/discord-sktrythmjs2/node_modules/@discordjs/rest/dist/index.js:640:13)$
2269     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)$
2270     at async SequentialHandler.runRequest (/root/discord-sktrythmjs2/node_modules/@discordjs/rest/dist/index.js:1021:23)$
2271     at async SequentialHandler.queueRequest (/root/discord-sktrythmjs2/node_modules/@discordjs/rest/dist/index.js:862:14)$
2272     at async REST.request (/root/discord-sktrythmjs2/node_modules/@discordjs/rest/dist/index.js:1387:22)$
2273     at async MessageManager.delete (/root/discord-sktrythmjs2/node_modules/discord.js/src/managers/MessageManager.js:255:5)$
2274     at async Message.delete (/root/discord-sktrythmjs2/node_modules/discord.js/src/structures/Message.js:816:5) {$
2275   requestBody: { files: undefined, json: undefined },$
2276   rawError: { message: 'Unknown Message', code: 10008 },$
2277   code: 10008,$
2278   status: 404,$
2279   method: 'DELETE',$
2280   url: 'https://discord.com/api/v10/channels/1097490591463505970/messages/1099631546358583338'$
2281 }$
